---
title: "Olympic_Mini-Project 01"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
---

# Data Visualization Project 01

I really love the Olympic Games season. It is one of my favorite times of year. Many athletes become heroes for generations, standing up for their nations and, more importantly, setting an example and inspiring future generations of athletes.

Through this data visualization, we can learn more about players, teams, sports, age and gender.


> ##### **This report aims to answer the following questions**: 

>   **Which countries dominate football?** 
>   **Which countries have the most medals?** 
>   **What is the ratio of female to male Olympic attendees?**

# Adding libraries to my data sets

library(ggplot2) 
library(readr)
library(tidyverse)
library(dplyr)
library(plyr)
library(rworldmap)
library(repr)

**Data Preparation**

**Characteristics of Data**: The All Years of Olympic Games project is being examined for representation through research into a variety of data sets. Occurrences (summer and winter), sport data, and art competition data are among the characteristics of the data. In addition to covering the years 1896 to 2020. From the viewpoints of visual representation and user experience, the Olympic Games data set is deemed to be worthwhile for study.

One data set will be used to create the visualizations. In reviewing the data set, I decided not to add any data and to make it more applicable and realistic. However, I changed the names of the columns and their values. The data spans from 1896 to 2020 covering the following categories:

**Name**

**AGE**

**Gender**

**Sport**

**Team**

